---
<<<<<<< HEAD
title: "hw_02"
=======
title: "hw_02_exercise1"
>>>>>>> 5e7660d505f2b8c397bb7e71aba3b0ef1ed8d6a8
output: 
  html_document:
    keep_md : true
editor options: 
  chunk_output_type: inline 
---

```{r load packages, warning = FALSE, message = FALSE}
library(gapminder)
library(tidyverse)
```
<<<<<<< HEAD
Exercise 1: Basic dplyr
=======
>>>>>>> 5e7660d505f2b8c397bb7e71aba3b0ef1ed8d6a8

```{r}
# 1.1 Using filter() to subset gapminder data to three countries of choice in the 1970’s.
gapminder %>%
filter (year > 1970 & year < 1980 | year == 1970,  
           country == "China" | country == "India" | country == "Pakistan")
```

```{r}
# 1.2 Using the pipe operator %>% to select “country” and “gdpPercap” from filtered dataset in 1.1. 
gapminder %>%
filter (year > 1970 & year < 1980 | year == 1970,  
           country == "China" | country == "India" | country == "Pakistan") %>%
 select(country, gdpPercap)

```

```{r}
# 1.3 Filtering gapminder to all entries that have experienced a drop in life expectancy.
gapminder %>%
 group_by(country) %>% 
 mutate(lifeExp_decrease = lifeExp - lag(lifeExp, 1, order_by = year)) %>%
 drop_na() %>%
 filter(lifeExp_decrease < 0)
```

```{r}
# 1.4 Filtering gapminder so that it shows the max GDP per capita experienced by each country.

gapminder %>%
  group_by(country, continent) %>%
  summarise(maxGDPperCap = max(gdpPercap))
```

```{r}
# 1.5 Producing a scatterplot of Canada’s life expectancy vs. GDP per capita using ggplot2, without defining a new variable.

gapminder %>% 
  filter(country == "Canada") %>% 
  ggplot(aes(gdpPercap, lifeExp)) + 
  geom_point() +
  scale_x_log10("GDP per capita", labels = scales::dollar_format()) + 
  labs(title="Canada", y="Life Expectancy")
  
```

<<<<<<< HEAD
Exercise 2: Explore individual variables with dplyr

I will be exploring two variables - life expectancy and continents

To understand the possible values in the variable "continents" I will explore the number of observation per continent and how many unique countries are there in each continent.

```{r}
gapminder %>%
  group_by(continent) %>%
  summarise(n = n(),
            n_countries = n_distinct(country)) %>%
  rename(number_of_observations = n) %>%
  rename(number_of_countries = n_countries)
  
``` 
Asia and Africa have the largest number of countries.

Now I will explore the variable life expectancy. I will first explore the range of the variable by continent in year 2007
```{r}
gapminder %>%
  filter(year == "2007") %>%
  group_by(continent) %>%
  summarise(min_lifeExp = min(lifeExp), max_lifeExp = max(lifeExp)) %>%
  mutate(range = max_lifeExp - min_lifeExp)
```
The range is largest for Asia and Africa. One of the reasons for this can be large number of countries as we saw in the previous table. However, Europe has only 3 countries less than Asia but its range of life expectancy is much smaller than Asia. 

Now I will explore the summaries of lifeExp by continent to find typical values. 
```{r}

```

=======
>>>>>>> 5e7660d505f2b8c397bb7e71aba3b0ef1ed8d6a8
